### ISSUE TITLE
kimsinsen

### ISSUE THREAD

**Issue by HasanBasri06** [teknasyon-bootcamp/homework2-BasriMaster#1]
![kimsinsen](https://user-images.githubusercontent.com/69991414/130787126-3dd4f2ad-6caf-4530-b4ad-8a1c75f78123.png)

**Comment by BasriMaster** [comment]
![](https://user-images.githubusercontent.com/69991414/130787126-3dd4f2ad-6caf-4530-b4ad-8a1c75f78123.png)

**Comment by erayaydin** [comment]
:laughing: muhteşem olmuş

**Comment by HasanBasri06** [comment]
teşekkürler hocam :)

Eray AYDIN ***@***.***>, 25 Ağu 2021 Çar, 17:46 tarihinde
şunu yazdı:
